=== katerinabaranova/HTP5_Medicine/data/medicins_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.medicine.com"
        xmlns:tns="http://www.medicine.com"
        elementFormDefault="qualified">

    <element name="AllMedicine">
        <complexType>
            <sequence>
                <element ref="tns:medicine" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="medicine" type="tns:Medicine" abstract="true"/>
    <element name="children-medicine" type="tns:Children-medicine" substitutionGroup="tns:medicine"/>
    <element name="adult-medicine" type="tns:Adult-medicine" substitutionGroup="tns:medicine"/>

    <complexType name="Medicine">
        <sequence>
            <element name="group">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="antibiotic"/>
                        <enumeration value="painkiller"/>
                        <enumeration value="vitamin"/>
                        <enumeration value="fever_reducer"/>
                        <enumeration value="antiviral"/>
                        <enumeration value="resolvent"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="analog" minOccurs="1" maxOccurs="unbounded">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[A-Z][a-zA-z\s]{1,30}"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="version" type="tns:Version"/>
        </sequence>
        <attribute name="name" type="string" use="optional" default="Nameless"/>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[a-z]\w{4,8}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>


    <complexType name="Version">
        <sequence>
            <element name="version_name">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[A-Z][a-zA-z\s]{1,30}"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="producers" minOccurs="1" maxOccurs="unbounded">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[A-Z][a-zA-z\s]{1,30}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="medicins_package" type="tns:Medicins-Package"/>
            <element name="dosage" type="tns:Dosage"/>
        </sequence>
    </complexType>

    <complexType name="Medicins-Package">
        <sequence>
            <element name="package_type">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[A-Z][a-zA-z\s]{1,30}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="quantity">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="1"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="price">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="1"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="Dosage">
        <sequence>
            <element name="prescribed_amount">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="1"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="frequency">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="1"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="Children-medicine">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="age_from" type="integer"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Adult-medicine">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="alcohol_allowed" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


</schema>

=== katerinabaranova/HTP5_Medicine/data/medicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:AllMedicine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:ns="http://www.medicine.com"
              xsi:schemaLocation="http://www.medicine.com medicins_schema.xsd">

    <ns:children_medicine name="Tyilinol" id="a546sd">
        <ns:group>fever_reducer</ns:group>
        <ns:analog>Paracetomol</ns:analog>
        <ns:analog>Ibyprophen</ns:analog>
        <ns:version>
            <ns:version_name>syrop</ns:version_name>
            <ns:producers>Acadia Pharmaceuticals</ns:producers>
            <ns:medicins_package>
                <ns:package_type>Bottle</ns:package_type>
                <ns:quantity>200</ns:quantity>
                <ns:price>30</ns:price>
            </ns:medicins_package>
            <ns:dosage>
                <ns:prescribed_amount>5</ns:prescribed_amount>
                <ns:frequency>3</ns:frequency>
            </ns:dosage>
        </ns:version>
        <ns:age_from>2</ns:age_from>
    </ns:children_medicine>

    <ns:children_medicine name="Centrum" id="f5445d">
        <ns:group>vitamin</ns:group>
        <ns:analog>VitaminKids</ns:analog>
        <ns:version>
            <ns:version_name>pill</ns:version_name>
            <ns:producers>Alphapharm</ns:producers>
            <ns:medicins_package>
                <ns:package_type>Container</ns:package_type>
                <ns:quantity>50</ns:quantity>
                <ns:price>15</ns:price>
            </ns:medicins_package>
            <ns:dosage>
                <ns:prescribed_amount>1</ns:prescribed_amount>
                <ns:frequency>1</ns:frequency>
            </ns:dosage>
        </ns:version>
        <ns:age_from>1</ns:age_from>
    </ns:children_medicine>

    <ns:adult_medicine name="IcyHot" id="g6782h">
        <ns:group>painkiller</ns:group>
        <ns:analog>Kapsikam</ns:analog>
        <ns:version>
            <ns:version_name>balm</ns:version_name>
            <ns:producers>Chattem Inc</ns:producers>
            <ns:medicins_package>
                <ns:package_type>Tube</ns:package_type>
                <ns:quantity>85</ns:quantity>
                <ns:price>20</ns:price>
            </ns:medicins_package>
            <ns:dosage>
                <ns:prescribed_amount>2</ns:prescribed_amount>
                <ns:frequency>5</ns:frequency>
            </ns:dosage>
        </ns:version>
        <ns:alcohol_allowed>true</ns:alcohol_allowed>
    </ns:adult_medicine>


</ns:AllMedicine>
